### ISSUE TITLE
レビュー漏れいろいろ

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#90]
# レビュー漏れ

## required をちゃんと付けてください

nullable の表現を required でするならば、ちゃんとすべてのオブジェクトに required 指定をしてください

### 参考までに

```ts
export interface Guest {
  id: string;
  color: Wristband;
}

export interface GuestDetail extends Guest {
  entered_at: string;
  exit_scheduled_time: string | null;
  exited_at: string | null;
  exh_id: string | null;
}
```

## TS がだめだったので all は null を返そう

```ts
export interface ExhStatus {
  count: {
    [key: string]: number;
  };
  limit: number;
  room_id: string | null;
}
```

## ActivityLog の guest の中身がおかしい

Wristband obj. を返すべきでは？

```yaml
    activityLog:
      properties:
        id:
          type: string
        timestamp:
          type: string
        guest:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
        exh_id:
          type: string
        log_type:
          type: string
          enum: [enter, exit]
```

## 表現統一

```diff
-      summary: 展示退室
+      summary: 展示退室処理
```

## 体裁

```diff
-            | :----------|  :-- |
+            | :-- | :-- |
```
こんな感じ？
